<a href="https://colab.research.google.com/github/rickiepark/SM-Summer-ML/blob/main/%ED%98%BC%EA%B3%B5%EB%A8%B8%EC%8B%A0_04_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [4]:
pd.unique(fish['Species'])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
fish_input = fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()

In [6]:
fish_input[:3]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961]])

In [7]:
fish_target = fish['Species'].to_numpy()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler

In [12]:
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)
kn.score(train_scaled, train_target), kn.score(test_scaled, test_target)

(0.8907563025210085, 0.85)

In [14]:
kn.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [15]:
kn.predict(test_scaled[:3])

array(['Perch', 'Smelt', 'Pike'], dtype=object)

In [16]:
kn.predict_proba(test_scaled[:3])

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [18]:
kn.predict_proba(test_scaled[:5])

array([[0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.33333333,
        0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.33333333,
        0.        , 0.        ]])

In [26]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')

In [27]:
bream_smelt_indexes

array([ True, False,  True, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False, False,  True, False,
       False,  True, False, False, False, False,  True, False, False,
        True,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False,  True, False,
        True, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True,  True, False, False,  True,
       False, False])

In [28]:
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

In [30]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

LogisticRegression()

In [31]:
lr.predict(train_bream_smelt[:5])

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [33]:
lr.predict_proba(train_bream_smelt[:5])

array([[0.99759855, 0.00240145],
       [0.02735183, 0.97264817],
       [0.99486072, 0.00513928],
       [0.98584202, 0.01415798],
       [0.99767269, 0.00232731]])

In [34]:
lr.coef_, lr.intercept_

(array([[-0.4037798 , -0.57620209, -0.66280298, -1.01290277, -0.73168947]]),
 array([-2.16155132]))

In [35]:
lr.decision_function(train_bream_smelt[:5])

array([-6.02927744,  3.57123907, -5.26568906, -4.24321775, -6.0607117 ])

In [37]:
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.9327731092436975, 0.925)

In [38]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [39]:
lr.predict_proba(test_scaled[:5])

array([[7.24962119e-06, 1.35114379e-02, 8.41283507e-01, 3.14327385e-04,
        1.35660262e-01, 6.67136890e-03, 2.55184724e-03],
       [7.14996969e-09, 2.55552480e-03, 4.39079515e-02, 3.37984180e-05,
        7.30920812e-03, 9.46188255e-01, 5.25482718e-06],
       [1.86538035e-05, 2.79615816e-06, 3.40568865e-02, 9.34811277e-01,
        1.50466238e-02, 1.60341031e-02, 2.96594224e-05],
       [1.09323066e-02, 3.40497502e-02, 3.05540604e-01, 6.60901798e-03,
        5.66580634e-01, 6.87213267e-05, 7.62189659e-02],
       [4.48967205e-06, 3.67276045e-04, 9.04006272e-01, 2.41283576e-03,
        8.94706737e-02, 2.40961911e-03, 1.32883359e-03]])

In [40]:
lr.decision_function(test_scaled[:5])

array([[ -6.4981111 ,   1.03223154,   5.16362367,  -2.72862525,
          3.33884865,   0.32652003,  -0.63448754],
       [-10.85948496,   1.92717508,   4.77101291,  -2.3984238 ,
          2.97805242,   7.84135903,  -4.25969068],
       [ -4.33528506,  -6.23308874,   3.17445241,   6.48676482,
          2.35757378,   2.42113805,  -3.87155526],
       [ -0.68336294,   0.45273744,   2.64699742,  -1.18665018,
          3.26453415,  -5.75278095,   1.25852507],
       [ -6.39707605,  -1.99274198,   5.81573587,  -0.11029771,
          3.50281047,  -0.11163174,  -0.70679887]])

In [41]:
lr.coef_, lr.intercept_

(array([[-1.49001259, -1.02909653,  2.59342992,  7.70358183, -1.20070797],
        [ 0.19618191, -2.01072007, -3.77974344,  6.50492519, -1.99481478],
        [ 3.562807  ,  6.34355461, -8.48969786, -5.75757213,  3.79306162],
        [-0.10458363,  3.60320663,  3.93067948, -3.61740078, -1.7506979 ],
        [-1.40060998, -6.0750259 ,  5.25969918, -0.87219289,  1.86043812],
        [-1.38528461,  1.49213609,  1.39225441, -5.67734711, -4.40097409],
        [ 0.6215019 , -2.32405484, -0.9066217 ,  1.71600589,  3.69369499]]),
 array([-0.09204689, -0.26289902,  3.25100925, -0.14740759,  2.65498221,
        -6.78787045,  1.38423249]))